### ISSUE TITLE
Return statement inside a generator error

### ISSUE THREAD

**Issue by dpiparo** [yuvipanda/jupyterhub-kubernetes-spawner#3]
Hi Yuvi,

thanks for putting together this nice piece of code.
I wonder if the repo is in a funny state since I setup jh and a kubernetes cluster but I get this error from the KubeSpawner:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "build/bdist.linux-x86_64/egg/kubespawner/__init__.py", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/kubespawner-0.1-py2.7.egg/kubespawner/spawner.py", line 215
> SyntaxError: 'return' with argument inside generator

Do you know what is going on?

Cheers,
    D

**Comment by dpiparo** [comment]
Hi,

it was a glitch in my setup. I cannot confirm I got the spawner working yet, but for sure that was not an issue :)

**Comment by yuvipanda** [comment]
Ah, this is python 3.x only at the moment...

On Fri, Mar 11, 2016 at 6:56 AM, dpiparo <notifications@github.com> wrote:

> Hi,
>
> it was a glitch in my setup. I cannot confirm I got the spawner working
> yet, but for sure that was not an issue :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yuvipanda/jupyterhub-kubernetes-spawner/issues/3#issuecomment-195400120>
> .
>



-- 
Yuvi Panda T
http://yuvi.in/blog
